// gen_icons.js: the status row's 16 px icons, rasterized by Chromium from the mock-up's own SVGs, so they're the
// pixels the mock-up shows. Owner: ui builder.
//
//   NODE_PATH=$(npm root -g) node firmware/components/ui/tools/gen_icons.js
//
// Needs Playwright with Chromium (preinstalled in the team's container). Writes ../src/ui_icons.c (committed, so the
// firmware build needs neither): white ARGB8888 images whose alpha is Chromium's coverage at 16 x 16 (the mock-up's
// .sys svg size in Bold Signal, 2.5cqw at 640 px). The SVG markup is copied from docs/mockup.html (wifiIcon(),
// headset, calGlyph, macIcon()); the script checks it's still there, so a changed icon in the mock-up fails here.
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const MOCKUP = path.join(__dirname, '../../../../docs/mockup.html');
const OUT = path.join(__dirname, '../src/ui_icons.c');
const ICONS = {
  wifi: '<svg class="ic-wifi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" aria-hidden="true"><path d="M2 9a15 15 0 0 1 20 0"/><path d="M5.5 12.5a10 10 0 0 1 13 0"/><path d="M9 16a5 5 0 0 1 6 0"/><circle cx="12" cy="19.5" r="1" fill="currentColor"/></svg>',
  wifi_off: '<svg class="ic-wifi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" aria-hidden="true"><g opacity=".4"><path d="M2 9a15 15 0 0 1 20 0"/><path d="M5.5 12.5a10 10 0 0 1 13 0"/><path d="M9 16a5 5 0 0 1 6 0"/></g><path d="M4 3l16 18"/></svg>',
  headset: '<svg class="ic-aside" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" aria-hidden="true"><path d="M4 15v-3a8 8 0 0 1 16 0v3"/><rect x="3" y="14" width="4.5" height="6.5" rx="1.5"/><rect x="16.5" y="14" width="4.5" height="6.5" rx="1.5"/></svg>',
  calendar: '<svg class="ic-aside" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2.5"/><path d="M3 10h18M8 3v4M16 3v4"/></svg>',
  mac: '<svg class="ic-mac" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="5" width="16" height="11" rx="1.5"/><path d="M2 19.5h20"/></svg>',
};
const PX = 16;

(async () => {
  const src = fs.readFileSync(MOCKUP, 'utf8');
  for (const [name, svg] of Object.entries(ICONS)) {
    // The mock-up writes these inside template strings; compare without the class attribute's surroundings.
    if (!src.includes(svg)) throw new Error(`the ${name} icon changed in docs/mockup.html; copy it here again`);
  }
  const b = await chromium.launch();
  const p = await b.newPage();
  const out = {};
  for (const [name, svg] of Object.entries(ICONS)) {
    const white = svg.replace('<svg ', `<svg xmlns="http://www.w3.org/2000/svg" width="${PX}" height="${PX}" color="#ffffff" `);
    out[name] = await p.evaluate(async ({ white, PX }) => {
      const img = new Image();
      img.src = 'data:image/svg+xml;base64,' + btoa(white);
      await img.decode();
      const c = document.createElement('canvas');
      c.width = c.height = PX;
      const x = c.getContext('2d');
      x.drawImage(img, 0, 0, PX, PX);
      return Array.from(x.getImageData(0, 0, PX, PX).data.filter((_, i) => i % 4 === 3));
    }, { white, PX });
  }
  await b.close();
  let c = '/* Generated by components/ui/tools/gen_icons.js from the SVG icons in docs/mockup.html. Do not edit. */\n'
    + '#include "ui_assets.h"\n\n';
  for (const [name, alpha] of Object.entries(out)) {
    const bytes = [];
    alpha.forEach(a => bytes.push(255, 255, 255, a));   // ARGB8888 in memory: B, G, R, A (white)
    c += `static const uint8_t icon_${name}_map[] = {\n`;
    for (let i = 0; i < bytes.length; i += 32) c += '    ' + bytes.slice(i, i + 32).map(v => '0x' + v.toString(16).padStart(2, '0')).join(',') + ',\n';
    c += '};\n';
    c += `const lv_image_dsc_t ui_icon_${name} = {\n`
      + `    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888, .w = ${PX}, .h = ${PX}, .stride = ${PX * 4}},\n`
      + `    .data_size = sizeof(icon_${name}_map),\n    .data = icon_${name}_map,\n};\n\n`;
  }
  fs.writeFileSync(OUT, c);
  console.log('wrote', OUT);
})();
