#!/usr/bin/env python3
"""
gen_tomatoes.py: build-time generator for the tomato images (standard library only; runs in ESP-IDF's Python and on
any Linux host). Owner: ui builder.

Reads assets/tomato_ripe.png and assets/tomato_unripe.png (32 x 32 RGBA, PixelLab, no faces) and writes one C file
with LVGL 9 image descriptors (ARGB8888):
  ui_tomato_ripe, ui_tomato_unripe   the sprites as they are
  ui_tomato_pale                     the ripe sprite with every pixel 55% of the way to white (upcoming sessions)
  ui_tomato_ripen[24]                the ripening frames: color breaks at the blossom end and spreads to the stem
                                     through yellow and orange (the mock-up's buildRipenFrames(), docs/mockup.html)

Usage: gen_tomatoes.py <ripe.png> <unripe.png> <out.c>

Skeleton: the PNG reader, the pale sprite and the C writer are real; ripen_frame() is a stub that returns the unripe
sprite. TODO(ui): port buildRipenFrames() exactly (skin mask where the sprites differ by more than 40, the blossom
point, the start map with the 5 lobes and the noise, SPAN .34, STEPS 5, ripenPixel()'s HSL path with the mute), and
test it against frames rendered by the mock-up in Chromium.
"""
import struct
import sys
import zlib


def read_png_rgba(path):
    data = open(path, 'rb').read()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', path
    pos, idat, w = 8, b'', 0
    while pos < len(data):
        n, = struct.unpack('>I', data[pos:pos + 4])
        kind = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + n]
        if kind == b'IHDR':
            w, h, depth, ctype, _, _, interlace = struct.unpack('>IIBBBBB', body)
            assert depth == 8 and ctype == 6 and interlace == 0, 'expects 8-bit RGBA, not interlaced'
        elif kind == b'IDAT':
            idat += body
        pos += 12 + n
    raw = zlib.decompress(idat)
    stride = w * 4
    rows, prev = [], bytearray(stride)
    for y in range(h):
        f = raw[y * (stride + 1)]
        line = bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - 4] if i >= 4 else 0
            b = prev[i]
            c = prev[i - 4] if i >= 4 else 0
            if f == 1:
                line[i] = (line[i] + a) & 255
            elif f == 2:
                line[i] = (line[i] + b) & 255
            elif f == 3:
                line[i] = (line[i] + ((a + b) >> 1)) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[i] = (line[i] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        rows.append(bytes(line))
        prev = line
    return w, h, b''.join(rows)


def pale(rgba):
    out = bytearray(rgba)
    for i in range(0, len(out), 4):
        for k in range(3):
            out[i + k] = round(rgba[i + k] + (255 - rgba[i + k]) * .55)
    return bytes(out)


def ripen_frame(green, red, w, h, f, frames):
    return green  # TODO(ui): port buildRipenFrames()


def c_image(name, w, h, rgba):
    argb = bytearray()
    for i in range(0, len(rgba), 4):
        r, g, b, a = rgba[i:i + 4]
        argb += bytes((b, g, r, a))  # LVGL ARGB8888 in memory: B, G, R, A
    hexes = ','.join('0x%02x' % v for v in argb)
    return (f'static const uint8_t {name}_map[] = {{{hexes}}};\n'
            f'const lv_image_dsc_t {name} = {{\n'
            f'    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888, .w = {w}, .h = {h}, .stride = {w * 4}}},\n'
            f'    .data_size = sizeof({name}_map),\n'
            f'    .data = {name}_map,\n}};\n')


def main():
    ripe_path, unripe_path, out_path = sys.argv[1:4]
    w, h, red = read_png_rgba(ripe_path)
    w2, h2, green = read_png_rgba(unripe_path)
    assert (w, h) == (w2, h2)
    frames = 24
    parts = ['/* Generated by components/ui/tools/gen_tomatoes.py. Do not edit. */\n#include "ui_assets.h"\n\n',
             c_image('ui_tomato_ripe', w, h, red), c_image('ui_tomato_unripe', w, h, green),
             c_image('ui_tomato_pale', w, h, pale(red))]
    for f in range(frames):
        parts.append(c_image(f'ui_tomato_ripen_{f}', w, h, ripen_frame(green, red, w, h, f, frames)))
    parts.append('static const lv_image_dsc_t *const ripen[] = {' +
                 ', '.join(f'&ui_tomato_ripen_{f}' for f in range(frames)) + '};\n\n')
    parts.append('const lv_image_dsc_t *ui_asset_tomato_ripe(void) { return &ui_tomato_ripe; }\n'
                 'const lv_image_dsc_t *ui_asset_tomato_unripe(void) { return &ui_tomato_unripe; }\n'
                 'const lv_image_dsc_t *ui_asset_tomato_pale(void) { return &ui_tomato_pale; }\n'
                 'const lv_image_dsc_t *ui_asset_tomato_ripening(int f)\n{\n'
                 f'    if (f < 0) f = 0;\n    if (f > {frames - 1}) f = {frames - 1};\n    return ripen[f];\n}}\n')
    with open(out_path, 'w') as fh:
        fh.write(''.join(parts))


if __name__ == '__main__':
    main()
