/*
 * ui_fonts.c: role -> font (ui_theme.h ui_font_role_t). Owner: ui builder.
 * The fonts are generated by ../tools/build_fonts.sh into ../fonts/ (see ../fonts/README.md for what each holds and
 * its flash size).
 */
#include "ui_fonts.h"

LV_FONT_DECLARE(ui_font_head_112)
LV_FONT_DECLARE(ui_font_head_100)
LV_FONT_DECLARE(ui_font_head_78)
LV_FONT_DECLARE(ui_font_head_62)
LV_FONT_DECLARE(ui_font_value_46)
LV_FONT_DECLARE(ui_font_value_28)
LV_FONT_DECLARE(ui_font_ampm_36)
LV_FONT_DECLARE(ui_font_ampm_17)
LV_FONT_DECLARE(ui_font_sub_19)
LV_FONT_DECLARE(ui_font_step_16)
LV_FONT_DECLARE(ui_font_step_16b)
LV_FONT_DECLARE(ui_font_kick_15)
LV_FONT_DECLARE(ui_font_sys_15)
LV_FONT_DECLARE(ui_font_foot_14)
LV_FONT_DECLARE(ui_font_label_12)

static const lv_font_t *const FONTS[UI_FONT_COUNT] = {
    [UI_FONT_HEAD_112] = &ui_font_head_112,     /* TinyBar Condensed Bold (tabular): timer, clock, BUSY */
    [UI_FONT_HEAD_100] = &ui_font_head_100,     /* Barlow Condensed Bold (proportional digits) */
    [UI_FONT_HEAD_78] = &ui_font_head_78,
    [UI_FONT_HEAD_62] = &ui_font_head_62,
    [UI_FONT_VALUE_46] = &ui_font_value_46,     /* tabular */
    [UI_FONT_VALUE_28] = &ui_font_value_28,
    [UI_FONT_AMPM_36] = &ui_font_ampm_36,
    [UI_FONT_AMPM_17] = &ui_font_ampm_17,
    [UI_FONT_SUB_19] = &ui_font_sub_19,         /* TinyBar Text Medium */
    [UI_FONT_STEP_16] = &ui_font_step_16,
    [UI_FONT_STEP_16_BOLD] = &ui_font_step_16b, /* TinyBar Text Bold, the letters of MiniBar-Setup only */
    [UI_FONT_KICK_15] = &ui_font_kick_15,       /* TinyBar Text Bold */
    [UI_FONT_SYS_15] = &ui_font_sys_15,         /* TinyBar Text SemiBold */
    [UI_FONT_FOOT_14] = &ui_font_foot_14,       /* TinyBar Text Medium */
    [UI_FONT_LABEL_12] = &ui_font_label_12,     /* TinyBar Text Bold */
};

const lv_font_t *ui_font(ui_font_role_t role)
{
    return (unsigned)role < UI_FONT_COUNT ? FONTS[role] : &ui_font_sys_15;
}
