#!/usr/bin/env python3
"""
gen_tz_table.py: build calendar/src/cal_tz_table.inc, the IANA name -> POSIX TZ rule table behind cal_tz_posix_for().

Owner: calendar builder.

Where the rules come from: every TZif file (version 2 and later) ends with a POSIX TZ string that describes the zone
from its last transition on; that footer is exactly what the bar needs (api.md section 15 suggests posix_tz_db, which
is built the same way). The script reads the footers from the `tzdata` Python package (pip install tzdata) so the
result doesn't depend on the build machine, and falls back to /usr/share/zoneinfo when the package isn't installed.
Links ("US/Pacific", "Asia/Calcutta") are kept, because browsers and older Macs still report some of them.

The output is compact: one string of NUL-separated names sorted by byte value (for a binary search), a uint16 offset
per name, a uint8 index per name into a pool of the distinct rules (tzdata 2026e: 598 names, 94 rules, about 12 KB).

    python3 tools/gen_tz_table.py            # writes src/cal_tz_table.inc next to this folder
    python3 tools/gen_tz_table.py --check    # exits 1 if the committed file is out of date
"""
import argparse
import os
import sys
import zoneinfo

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'cal_tz_table.inc')
SKIP = {'Factory', 'localtime', 'posixrules'}


def tzif_footer(data, name):
    if data[:4] != b'TZif':
        raise ValueError(f'{name}: not a TZif file')
    if data[4:5] == b'\0':
        raise ValueError(f'{name}: version 1 TZif has no POSIX footer')
    footer = data.rstrip(b'\n').rsplit(b'\n', 1)[-1].decode('ascii')
    if not footer:
        raise ValueError(f'{name}: empty POSIX footer')
    return footer


def load():
    try:
        import importlib.resources as res
        import tzdata  # noqa: F401
        version = 'tzdata ' + tzdata.IANA_VERSION

        def read(name):
            p = res.files('tzdata').joinpath('zoneinfo', *name.split('/'))
            return p.read_bytes() if p.is_file() else None
        names = zoneinfo.available_timezones()
    except ImportError:
        root = '/usr/share/zoneinfo'
        version = 'system zoneinfo (' + root + ')'

        def read(name):
            p = os.path.join(root, name)
            return open(p, 'rb').read() if os.path.isfile(p) else None
        names = zoneinfo.available_timezones()
    rules = {}
    for n in sorted(names):
        if n in SKIP:
            continue
        data = read(n)
        if data is None:
            continue
        rules[n] = tzif_footer(data, n)
    return version, rules


def c_string(s):
    out = []
    for ch in s:
        if ch in '\\"':
            out.append('\\' + ch)
        else:
            out.append(ch)
    return ''.join(out)


def render(version, rules):
    names = sorted(rules, key=lambda s: s.encode())
    pool = sorted(set(rules.values()))
    if len(pool) > 255:
        raise SystemExit('more than 255 distinct rules: widen TZ_RULE_INDEX to uint16_t')
    pool_off, off = [], 0
    for p in pool:
        pool_off.append(off)
        off += len(p) + 1
    name_off, off = [], 0
    for n in names:
        name_off.append(off)
        off += len(n) + 1
    if off > 65535:
        raise SystemExit('names exceed 64 KB: widen the offsets')
    lines = [
        '/* cal_tz_table.inc: IANA time zone name -> POSIX TZ rule. GENERATED by tools/gen_tz_table.py from',
        f' * {version}; do not edit by hand. {len(names)} names, {len(pool)} distinct rules. */',
        '',
        f'#define TZ_NAME_COUNT {len(names)}',
        f'#define TZ_RULE_COUNT {len(pool)}',
        '',
        'static const char TZ_RULES[] =',
    ]
    for p in pool:
        lines.append(f'    "{c_string(p)}\\0"')
    lines[-1] += ';'
    lines.append('')
    lines.append('static const uint16_t TZ_RULE_OFF[TZ_RULE_COUNT] = {')
    for i in range(0, len(pool_off), 12):
        lines.append('    ' + ', '.join(str(x) for x in pool_off[i:i + 12]) + ',')
    lines.append('};')
    lines.append('')
    lines.append('static const char TZ_NAMES[] =')
    for n in names:
        lines.append(f'    "{c_string(n)}\\0"')
    lines[-1] += ';'
    lines.append('')
    lines.append('static const uint16_t TZ_NAME_OFF[TZ_NAME_COUNT] = {')
    for i in range(0, len(name_off), 12):
        lines.append('    ' + ', '.join(str(x) for x in name_off[i:i + 12]) + ',')
    lines.append('};')
    lines.append('')
    lines.append('static const uint8_t TZ_NAME_RULE[TZ_NAME_COUNT] = {')
    idx = [pool.index(rules[n]) for n in names]
    for i in range(0, len(idx), 16):
        lines.append('    ' + ', '.join(str(x) for x in idx[i:i + 16]) + ',')
    lines.append('};')
    lines.append('')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='fail if the committed table differs')
    ap.add_argument('--out', default=OUT)
    a = ap.parse_args()
    version, rules = load()
    text = render(version, rules)
    if a.check:
        old = open(a.out).read() if os.path.exists(a.out) else ''
        if old != text:
            print('cal_tz_table.inc is out of date (or built from other tzdata): run tools/gen_tz_table.py')
            return 1
        print('cal_tz_table.inc is up to date')
        return 0
    with open(a.out, 'w') as f:
        f.write(text)
    size = sum(len(n) + 1 for n in rules) + sum(len(p) + 1 for p in set(rules.values())) + 3 * len(rules)
    print(f'wrote {os.path.relpath(a.out)}: {len(rules)} names, {len(set(rules.values()))} rules, about {size} bytes '
          f'({version})')
    return 0


if __name__ == '__main__':
    sys.exit(main())
